# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90d964fd6e987abb2cb75ed7a469ebd4c1d10985c87d782f5f491f72253674bc72cca754d82398762a0ca081b340d7d9cbc15c1b265a4b78a907cb8529a87b0f

test:
  secret_key_base: fd64b3066cb4202c5a49d34543e350691656469c92faaf17b44ad6bf1d08b11fc50c2ffe399baf913e7a383d2a94ab57ab2b7865e7ba604498044612717fa09d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
